### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by wmantly** [kiler129/relax-intel-rmrr#7] opened 2021-04-15 05:33 UTC
```
###########################################################
############ STEP 2 - DOWNLOAD CODE TO COMPILE ############
###########################################################
Step 2.0: Creating working directory
Step 2.1: Downloading Proxmox kernel toolchain & patches
Cloning into 'pve-kernel'...
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 38 (delta 1), reused 22 (delta 1)
Receiving objects: 100% (38/38), 381.67 KiB | 977.00 KiB/s, done.
Resolving deltas: 100% (1/1), done.
Cloning into 'relax-intel-rmrr'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 14 (delta 1), reused 10 (delta 1), pack-reused 0
Unpacking objects: 100% (14/14), done.
Step 2.2: Downloading base kernel
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2585    0  2585    0     0   6967      0 --:--:-- --:--:-- --:--:--  6948

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Promox 6.3-6

**Comment by kiler129** [comment] 2021-04-16 05:00
Duplicate of https://github.com/kiler129/relax-intel-rmrr/issues/5 and fixed in https://github.com/kiler129/relax-intel-rmrr/pull/8

Thanks for the report!

**Closed by kiler129** 2021-04-16 05:00 UTC
